Add OIDC role mapping
jfrog/terraform-provider-platform pull request #137
Opened 2024-10-09 14:48 UTC by akhter-ali-idexx

2024-10-09 16:03 UTC, alexhung requested changes
Please also add test for the `roles` scope. See https://github.com/jfrog/terraform-provider-platform/blob/main/pkg/platform/resource_oidc_identity_mapping_test.go#L130 for example.

2024-10-09 16:03 UTC, alexhung commented on pkg/platform/resource_oidc_identity_mapping.go
> +								regexp.MustCompile(`^(applied-permissions\/admin|applied-permissions\/user|applied-permissions\/groups|applied-permissions\/roles:.+)$`),
The trailing `:` is missing for the `groups`.

2024-10-09 16:36 UTC, akhter-ali-idexx commented
> Please also add test for the `roles` scope. See https://github.com/jfrog/terraform-provider-platform/blob/main/pkg/platform/resource_oidc_identity_mapping_test.go#L130 for example.

Done

2024-10-09 16:38 UTC, alexhung commented
> > Please also add test for the `roles` scope. See https://github.com/jfrog/terraform-provider-platform/blob/main/pkg/platform/resource_oidc_identity_mapping_test.go#L130 for example.
> 
> Done

@akhter-ali-idexx Excellent!

Can you also try to sign the CLA? The bot may fails but that's ok as long as you sign.

2024-10-09 16:55 UTC, akhter-ali-idexx commented
> @akhter-ali-idexx See [test failures](https://github.com/jfrog/terraform-provider-platform/actions/runs/11259232965/job/31307944840) ![Screenshot 2024-10-09 at 9 52 08 AM](https://private-user-images.githubusercontent.com/27263/375058267-c1f5c080-652b-4c14-9095-4c7faea81e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTMwMzksIm5iZiI6MTcyODQ5MjczOSwicGF0aCI6Ii8yNzI2My8zNzUwNTgyNjctYzFmNWMwODAtNjUyYi00YzE0LTkwOTUtNGM3ZmFlYTgxZTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE2NTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZDZmNTZhYTg1YjBiOWUzYzQ1YmQ1MGM5M2MyZTBhZTBjZWE0YThiYmMyYTQ4M2ZlMDJhYmUyZjhjYTEwZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Db2SvHY3iJiVL1PchCtcyG-l-KiSHU563ro_Y-7yH_0)

Wow, I completely missed that, lol.  Test execution added

2024-10-10 12:11 UTC, akhter-ali-idexx commented
@alexhung Please do let me know if I've missed anything else, I'd like to use asap.  Thank you!

2024-10-10 16:33 UTC, alexhung approved these changes
Look good enough for now. I'll take this from here and get it to be in a releasable state.

2024-10-10 16:33 UTC, alexhung commented on pkg/platform/resource_oidc_identity_mapping.go
> +								regexp.MustCompile(`^(applied-permissions\/admin|applied-permissions\/user|applied-permissions\/groups|applied-permissions\/roles:.+)$`),
The `:` is still missing. Should be `applied-permissions\/groups:`

2024-10-10 16:33 UTC, merged